### ISSUE TITLE
Group ID can not be found in download.

### ISSUE THREAD

**Issue by ccdasa** [iw4p/telegram-cloud#27]
`tgcloud -m download -n x -u -123456789 -p "/Users/me/Desktop/" -c "test"`

When I use this command with a groupID I get a error message.

Uploading with the same groupID works and uploading and downloading to me works as well. Am I doing anything wrong?

Thank you for the help!

Awesome tool!

Additional Info:
* groupID is replaced
* OS = macOS

The error message:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tgcloud", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegramcloud/__main__.py", line 71, in cli
    client.loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telegramcloud/__main__.py", line 45, in main
    async for message in client.iter_messages(entity=username, search=args.caption):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telethon/client/messages.py", line 26, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telethon/client/users.py", line 570, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "-123456789"
```

**Comment by iw4p** [comment]
Hello
Thank you for reporting this problem.
It's my bad!
Now it's working fine, test it again and make sure you are on version 1.4.4, not older versions.

**Comment by ccdasa** [comment]
Works now! Thank you for the quick fix!
